In [1]:
import math,numpy

# full rating
puf = [ [(0,0,4),(0,1,3),(0,2,5),(0,3,1),(0,4,5),(0,5,5)],
        [(1,0,2),(1,1,3),(1,2,4),(1,3,4),(1,4,5),(1,5,3)],
        [(2,0,5),(2,1,4),(2,2,4),(2,3,5),(2,4,4),(2,5,5)],
        [(3,0,4),(3,1,4),(3,2,3),(3,3,3),(3,4,4),(3,5,4)],
        [(4,0,3),(4,1,5),(4,2,5),(4,3,4),(4,4,5),(4,5,3)],
        [(5,0,4),(5,1,2),(5,2,4),(5,3,5),(5,4,3),(5,5,4)]]

pvf = [ [(0,0,4),(0,1,2),(0,2,5),(0,3,4),(0,4,3),(0,5,4)],
        [(1,0,3),(1,1,3),(1,2,4),(1,3,4),(1,4,5),(1,5,2)],
        [(2,0,5),(2,1,4),(2,2,4),(2,3,3),(2,4,5),(2,5,4)],
        [(3,0,1),(3,1,4),(3,2,5),(3,3,3),(3,4,4),(3,5,5)],
        [(4,0,5),(4,1,5),(4,2,4),(4,3,4),(4,4,5),(4,5,3)],
        [(5,0,5),(5,1,3),(5,2,5),(5,3,4),(5,4,3),(5,5,4)]]
'''
# 5 rating each        
pu = [  [        (0,1,3),(0,2,5),(0,3,1),(0,4,5),(0,5,5)],
        [(1,0,2),        (1,2,4),(1,3,4),(1,4,5),(1,5,3)],
        [(2,0,5),(2,1,4),        (2,3,5),(2,4,4),(2,5,5)],
        [(3,0,4),(3,1,4),(3,2,3),        (3,4,4),(3,5,4)],
        [(4,0,3),(4,1,5),(4,2,5),(4,3,4),        (4,5,3)],
        [(5,0,4),(5,1,2),(5,2,4),(5,3,5),(5,4,3)        ]]

pv = [  [        (0,1,2),(0,2,5),(0,3,4),(0,4,3),(0,5,4)],
        [(1,0,3),        (1,2,4),(1,3,4),(1,4,5),(1,5,2)],
        [(2,0,5),(2,1,4),        (2,3,3),(2,4,5),(2,5,4)],
        [(3,0,1),(3,1,4),(3,2,5),        (3,4,4),(3,5,5)],
        [(4,0,5),(4,1,5),(4,2,4),(4,3,4),        (4,5,3)],
        [(5,0,5),(5,1,3),(5,2,5),(5,3,4),(5,4,3)        ]]

# 4 ratings each    
pu = [  [(0,0,4),(0,1,3),(0,2,5),(0,3,1),(0,4,5),(0,5,5)],
        [(1,0,2),(1,1,3),(1,2,4),(1,3,4),(1,4,5),(1,5,3)],
        [(2,0,5),(2,1,4),(2,2,4),(2,3,5),(2,4,4),(2,5,5)],
        [(3,0,4),(3,1,4),(3,2,3),(3,3,3),(3,4,4),(3,5,4)],
        [(4,0,3),(4,1,5),(4,2,5),(4,3,4),(4,4,5),(4,5,3)],
        [(5,0,4),(5,1,2),(5,2,4),(5,3,5),(5,4,3),(5,5,4)]]

pv = [  [(0,0,4),(0,1,2),(0,2,5),(0,3,4),(0,4,3),(0,5,4)],
        [(1,0,3),(1,1,3),(1,2,4),(1,3,4),(1,4,5),(1,5,2)],
        [(2,0,5),(2,1,4),(2,2,4),(2,3,3),(2,4,5),(2,5,4)],
        [(3,0,1),(3,1,4),(3,2,5),(3,3,3),(3,4,4),(3,5,5)],
        [(4,0,5),(4,1,5),(4,2,4),(4,3,4),(4,4,5),(4,5,3)],
        [(5,0,5),(5,1,3),(5,2,5),(5,3,4),(5,4,3),(5,5,4)]]

# 3 ratings each     
pu = [  [(0,0,4),(0,1,3),(0,2,5),(0,3,1),(0,4,5),(0,5,5)],
        [(1,0,2),(1,1,3),(1,2,4),(1,3,4),(1,4,5),(1,5,3)],
        [(2,0,5),(2,1,4),(2,2,4),(2,3,5),(2,4,4),(2,5,5)],
        [(3,0,4),(3,1,4),(3,2,3),(3,3,3),(3,4,4),(3,5,4)],
        [(4,0,3),(4,1,5),(4,2,5),(4,3,4),(4,4,5),(4,5,3)],
        [(5,0,4),(5,1,2),(5,2,4),(5,3,5),(5,4,3),(5,5,4)]]

pv = [  [(0,0,4),(0,1,2),(0,2,5),(0,3,4),(0,4,3),(0,5,4)],
        [(1,0,3),(1,1,3),(1,2,4),(1,3,4),(1,4,5),(1,5,2)],
        [(2,0,5),(2,1,4),(2,2,4),(2,3,3),(2,4,5),(2,5,4)],
        [(3,0,1),(3,1,4),(3,2,5),(3,3,3),(3,4,4),(3,5,5)],
        [(4,0,5),(4,1,5),(4,2,4),(4,3,4),(4,4,5),(4,5,3)],
        [(5,0,5),(5,1,3),(5,2,5),(5,3,4),(5,4,3),(5,5,4)]]
'''
# 2 ratings each
pu = [  [                                (0,4,5),(0,5,5)],
        [(1,0,2)                                ,(1,5,3)],
        [(2,0,5),(2,1,4)                                ],
        [        (3,1,4),(3,2,3)                        ],
        [                (4,2,5),(4,3,4)                ],
        [                        (5,3,5),(5,4,3)        ]]

pv = [  [        (0,1,2),(0,2,5)                        ],
        [                (1,2,4),(1,3,4)                ],
        [                        (2,3,3),(2,4,5)        ],
        [                                (3,4,4),(3,5,5)],
        [(4,0,5),                                (4,5,3)],
        [(5,0,5),(5,1,3)                                ]]

In [2]:
# random ratings for item
# row: number of items
# column: number of latent features
V = numpy.random.rand(6,3)
'''V = numpy.mat([[  0.15968384, 0.94411985, 0.83651085],
                [ 0.73573009, 0.24906915, 0.85338239],
                [ 0.25605814, 0.69905325, 0.50900407],
                [ 0.24058435, 0.31848888, 0.60233653],
                [ 0.24237479, 0.15293281, 0.22240255],
                [ 0.03943766, 0.19287528, 0.95094265]])
'''

# create a 6 by 3 matrix with 0
# row: number of user:
# column: number of latent features
U = numpy.mat(numpy.zeros([6,3]))

# Bayesian prior lamda
L = 0.5


In [3]:
for iter in range(10):

#    print("\n----- ITER %s -----" % (iter + 1))

# fixing V and minimizing U
#    print("U before fixing V and minimizing U = \n %s" %U)
    urs = []
    for uset in pu:
        vo = []
        pvo = []
        for i,j,p in uset:
            vor = []
            for k in range(3):
                vor.append(V[j,k])
            vo.append(vor)
            pvo.append(p)
        vo = numpy.mat(vo)
        # linalg.inv: Compute the (multiplicative) inverse of a matrix.
        # adding a prior matrix to the covariance matrix.
        ur = numpy.linalg.inv(vo.T*vo + L*numpy.mat(numpy.eye(3))) * vo.T * numpy.mat(pvo).T
        urs.append(ur.T)
    # vstack: Stack arrays in sequence vertically (row wise).
    U = numpy.vstack(urs)
#    print("U after fixing V and minimizing U = \n %s \n" %U)

# fixing U and minimizing V
#    print("V before fixing U and minimizing V = \n %s" %V)
    vrs = []
    for vset in pv:
        uo = []
        puo = []
        for j,i,p in vset:
            uor = []
            for k in range(3):
                uor.append(U[i,k])
            uo.append(uor)
            puo.append(p)
        uo = numpy.mat(uo)
        vr = numpy.linalg.inv(uo.T*uo + L*numpy.mat(numpy.eye(3))) * uo.T * numpy.mat(puo).T
        vrs.append(vr.T)
    V = numpy.vstack(vrs)
#    print("V after fixing U and minimizing V = \n %s \n" %V)

# calcurate error
    err = 0.
    n = 0.
    for uset in puf:
        for i,j,p in uset:
            err += (p - (U[i]*V[j].T))**2
            n += 1
    print("Possible rating error after %s iteration = %5.5f\n" %(iter+1, math.sqrt(err/n)))
    #print("Accuracy after {} iteration = {}" .format(iter+1, math.sqrt(err/n)))

Possible rating error after 1 iteration = 1.36160

Possible rating error after 2 iteration = 1.37649

Possible rating error after 3 iteration = 1.36659

Possible rating error after 4 iteration = 1.35805

Possible rating error after 5 iteration = 1.34483

Possible rating error after 6 iteration = 1.33025

Possible rating error after 7 iteration = 1.31741

Possible rating error after 8 iteration = 1.30623

Possible rating error after 9 iteration = 1.29541

Possible rating error after 10 iteration = 1.28430



In [4]:
print("U after %sth iterations = \n %s \n" %((iter +1),U))
print("V after %sth iterations = \n %s \n" %((iter +1),V.T))
print("Prediction of ratings of user i (row) against item j (column) after %sth iteration is U*V.T =\n" %(iter+1))
print(U*V.T)

U after 10th iterations = 
 [[ 1.32163627 -0.17898298  2.17055147]
 [ 0.70219617  0.25866124  1.21112706]
 [ 0.56991022  1.86053787  0.98810026]
 [ 0.88346119  1.4448584   0.77920262]
 [ 1.7705118   0.61344863  1.2107002 ]
 [ 0.72853595  1.01344921  1.72806928]] 

V after 10th iterations = 
 [[ 0.54861641  0.88571444  1.6276014   0.7383649   0.96012919  0.96997601]
 [ 1.76050903  1.45823534  0.50406478  1.00200118 -0.25785373  0.09509074]
 [ 0.95108648  0.78625726  1.1037716   1.71078572  1.51574008  1.63007283]] 

Prediction of ratings of user i (row) against item j (column) after 10th iteration is U*V.T =

[[2.47435235 2.61620487 4.4566711  4.50985715 4.60508486 4.80309285]
 [1.99249837 1.95139169 2.61008514 2.84963476 2.4432561  2.67993505]
 [4.52792461 3.99478077 2.95605529 3.97549065 1.56514396 2.34039455]
 [3.76945664 3.50209162 3.02628663 3.43311526 1.65674339 2.26448584]
 [3.20279427 3.41464215 4.52724183 3.99320863 3.37684686 3.74921677]
 [3.82741658 3.48182926 3.60400398 4.50