# Alternating Least Squares (ALS)

----------------------------------------------------------------------

### pu: Rating of user i against item j. Rating can be missing.

### pv: Rating of item i against user j. Rating can be missing.

### Transpose(pu) = pv

In [9]:
import math,numpy

pu = [  [(0,0,1),(0,1,22),(0,2,1),(0,3,1),        (0,5,0)],
        [(1,0,1),(1,1,32),(1,2,0),(1,3,0),(1,4,1),(1,5,0)],
        [(2,0,0),(2,1,18),(2,2,1),(2,3,1),(2,4,0),(2,5,1)],
        [(3,0,1),(3,1,40),(3,2,1),(3,3,0),(3,4,0),(3,5,1)],
        [(4,0,0),(4,1,40),(4,2,0),        (4,4,1),(4,5,0)],
        [(5,0,0),(5,1,25),(5,2,1),(5,3,1),(5,4,1)        ]]


pv = [  [(0,0,1),(0,1,1),(0,2,0),(0,3,1),(0,4,0),(0,5,0)],
        [(1,0,22),(1,1,32),(1,2,18),(1,3,40),(1,4,40),(1,5,25)],
        [(2,0,1),(2,1,0),(2,2,1),(2,3,1),(2,4,0),(2,5,1)],
        [(3,0,1),(3,1,0),(3,2,1),(3,3,0),        (3,5,1)],
        [        (4,1,1),(4,2,0),(4,3,0),(4,4,1),(4,5,1)],
        [(5,0,0),(5,1,0),(5,2,1),(5,3,1),(5,4,0)        ]]


### V: randomly generated inital ratings for 6 items by 3 latent features

### U: initial zero matrix for 6 users by 3 latent features 

#### Latent feature:  "Coolness is an example of a latent feature since it’s unobserved and not measurable directly. It also reduces dimensions because it’s a combination of many “features” we’ve observed about the person and implictly weighted in our mind."

### L: Bayesian prior for adding a penalty term for large coefficients to tackle overfitting

In [2]:
# random ratings for item
# row: number of items
# column: number of latent features
V = numpy.mat([[  0.15968384, 0.94411985, 0.83651085],
                [ 0.73573009, 0.24906915, 0.85338239],
                [ 0.25605814, 0.69905325, 0.50900407],
                [ 0.24058435, 0.31848888, 0.60233653],
                [ 0.24237479, 0.15293281, 0.22240255],
                [ 0.03943766, 0.19287528, 0.95094265]])

# create a 6 by 3 matrix with 0
# row: number of user:
# column: number of latent features
U = numpy.mat(numpy.zeros([6,3]))

# Bayesian prior lamda
L = 0.03

### Print pu, pv and V, not mandatory

In [10]:
print("pu =\n %s" %pu)
print("")

print("pv =\n %s" %pv)
print("")

print("V = \n %s" %V)

pu =
 [[(0, 0, 1), (0, 1, 22), (0, 2, 1), (0, 3, 1), (0, 5, 0)], [(1, 0, 1), (1, 1, 32), (1, 2, 0), (1, 3, 0), (1, 4, 1), (1, 5, 0)], [(2, 0, 0), (2, 1, 18), (2, 2, 1), (2, 3, 1), (2, 4, 0), (2, 5, 1)], [(3, 0, 1), (3, 1, 40), (3, 2, 1), (3, 3, 0), (3, 4, 0), (3, 5, 1)], [(4, 0, 0), (4, 1, 40), (4, 2, 0), (4, 4, 1), (4, 5, 0)], [(5, 0, 0), (5, 1, 25), (5, 2, 1), (5, 3, 1), (5, 4, 1)]]

pv =
 [[(0, 0, 1), (0, 1, 1), (0, 2, 0), (0, 3, 1), (0, 4, 0), (0, 5, 0)], [(1, 0, 22), (1, 1, 32), (1, 2, 18), (1, 3, 40), (1, 4, 40), (1, 5, 25)], [(2, 0, 1), (2, 1, 0), (2, 2, 1), (2, 3, 1), (2, 4, 0), (2, 5, 1)], [(3, 0, 1), (3, 1, 0), (3, 2, 1), (3, 3, 0), (3, 5, 1)], [(4, 1, 1), (4, 2, 0), (4, 3, 0), (4, 4, 1), (4, 5, 1)], [(5, 0, 0), (5, 1, 0), (5, 2, 1), (5, 3, 1), (5, 4, 0)]]

V = 
 [[ 0.45756647  0.92511124  0.37769859]
 [ 0.80747524 -1.31669286 -0.40746827]
 [ 0.06117348  0.26890639  0.58875359]
 [ 0.02190391  0.2856264   0.74049089]
 [-0.54678196 -1.26452109 -0.64602637]
 [-0.47115985 -0.8275

### Fixing V and minimizing U

### Fixing U and minimizing V

### 5 iterations in total

### Calculating error in the end

In [11]:
for iter in range(5):

    print("\n----- ITER %s -----" % (iter + 1))

# fixing V and minimizing U
    print("U before ALS = \n %s" %U)
    urs = []
    for uset in pu:
        vo = []
        pvo = []
        for i,j,p in uset:
            vor = []
            for k in range(3):
                vor.append(V[j,k])
            vo.append(vor)
            pvo.append(p)
        vo = numpy.mat(vo)
        # linalg.inv: Compute the (multiplicative) inverse of a matrix.
        # adding a prior matrix to the covariance matrix.
        ur = numpy.linalg.inv(vo.T*vo + L*numpy.mat(numpy.eye(3))) * vo.T * numpy.mat(pvo).T
        urs.append(ur.T)
    # vstack: Stack arrays in sequence vertically (row wise).
    U = numpy.vstack(urs)
    print("U after ALS = \n %s \n" %U)

# fixing U and minimizing V
    print("V before ALS = \n %s" %V)
    vrs = []
    for vset in pv:
        uo = []
        puo = []
        for j,i,p in vset:
            uor = []
            for k in range(3):
                uor.append(U[i,k])
            uo.append(uor)
            puo.append(p)
        uo = numpy.mat(uo)
        vr = numpy.linalg.inv(uo.T*uo + L*numpy.mat(numpy.eye(3))) * uo.T * numpy.mat(puo).T
        vrs.append(vr.T)
    V = numpy.vstack(vrs)
    print("V after ALS = \n %s \n" %V)

# calcurate error
    err = 0.
    n = 0.
    for uset in pu:
        for i,j,p in uset:
            err += (p - (U[i]*V[j].T)[0,0])**2
            n += 1
    print("Error = %s" %math.sqrt(err/n))


----- ITER 1 -----
U before ALS = 
 [[ 15.80920666  -8.18261494   3.72552172]
 [ 22.17681197 -11.78741183   3.48209366]
 [ 12.2687637   -7.28862242   3.70679897]
 [ 27.82549981 -15.0521207    5.58723872]
 [ 27.42304481 -14.67519097   3.64969418]
 [ 16.59391153 -10.26117549   4.71711301]]
U after ALS = 
 [[ 15.42801002  -8.0227096    3.54528738]
 [ 21.6562059  -11.56427606   3.17211423]
 [ 11.98344689  -7.14343224   3.50862769]
 [ 27.16353041 -14.76653283   5.20081837]
 [ 26.79572526 -14.3961688    3.25709329]
 [ 16.21029994 -10.06952244   4.43758599]] 

V before ALS = 
 [[ 0.45756647  0.92511124  0.37769859]
 [ 0.80747524 -1.31669286 -0.40746827]
 [ 0.06117348  0.26890639  0.58875359]
 [ 0.02190391  0.2856264   0.74049089]
 [-0.54678196 -1.26452109 -0.64602637]
 [-0.47115985 -0.82757264  0.23464793]]
V after ALS = 
 [[ 0.46156164  0.91866728  0.37260084]
 [ 0.84185434 -1.2986571  -0.391088  ]
 [ 0.05419593  0.24058937  0.58110695]
 [ 0.01189083  0.248941    0.73040161]
 [-0.55907471 -

## Final predictions for ratings of user i against item j

In [16]:
print(U*V.T)

[[ 1.07234852 22.01616681  0.98820861  0.78705037 -0.82323747  0.18750713]
 [ 0.53757317 32.00907462  0.20860488 -0.30874106  0.55965533  0.11859084]
 [ 0.27425029 17.99268848  0.97225581  0.9184595   0.08416286  1.11542051]
 [ 0.8916418  40.00924154  0.93326649  0.44673761  0.19375501  0.66528153]
 [ 0.38355781 39.98226418 -0.10276711 -0.81706397  1.19954201  0.08437046]
 [-0.10816063 24.98986991  1.03485765  0.92704189  0.87248467  1.79836781]]
